source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftJSONRPC_Example', :exclusive => true do
  pod "SwiftJSONRPC", :path => "../"
end

target 'SwiftJSONRPC_Tests', :exclusive => true do
  pod "SwiftJSONRPC", :path => "../"

  
end
