source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

xcodeproj '../SwiftJSONRPC.xcodeproj'
workspace '../SwiftJSONRPC.xcworkspace'

target 'SwiftJSONRPCTests', :exclusive => true do
  pod "SwiftJSONRPC", :path => "../"
end
