source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

workspace '../SwiftJSONRPC.xcworkspace'
project '../SwiftJSONRPC.xcodeproj'

target 'SwiftJSONRPCTests' do
  pod "SwiftJSONRPC", :path => "../"
end
